export const data = [
  {
    name: "Solo Leveling",
    released: "2021-03-03",
    metacritic: 10,
    description: `Il y a 10 ans, des personnes ont reçu le pouvoir de chasser des monstres via la Porte qui connecte le monde réel au monde des monstres.<br>Sung Jin-Woo est un chasseur de rang E qui risque sa vie dans les donjons les plus faibles et gagne à peine de l'argent.<br>Jusqu'à ce qu'il trouve un donjon caché difficile et reçoive un pouvoir étrange qui lui permet de monter de niveau en effectuant des quêtes et en chassant des monstres, passant ainsi du plus faible au plus fort chasseur de rang S.<br>`,
    background_image: "images/Solo_Leveling.jpg",
  },
    {
      name: "Reincarnation of the Suicidal Battle God",
      released: "2021-06-26",
      metacritic: 10,
      description: `Zéphyr est le plus puissant des humains et le seul survivant dans un monde dévasté par Tartaros, le Dieu des démons.<br> Les Dieux qui trouvaient la souffrance des humains divertissante lui ont donné une deuxième chance de remonter le temps pour sauver l'humanité.<br> Cette fois, Zéphyr se battra jusqu'au bout et brisera tout obstacle pour vaincre les Dieux une bonne fois pour toutes.<br>`,
      background_image: "images/Reincarnation_of_the_Suicidal_Battle_God.jpg",
    },
    {
      name: "The Constelation That Returned From Hell",
      released: "2021-04-07",
      metacritic: 9.4,
      description:
        "Après des centaines d'années en Enfer, je suis revenu dans le but de sauver l'humanité !",
      background_image: "images/The_Constelation_That_Returned_From_Hell.jpg",
    },
    {
      name: "I Reincarnated As The Crazed Heir",
      released: "2021-07-23",
      metacritic: 9.2,
      description: `Yang Ja-Gak a été empoisonné pendant la guerre politique des sectes. <br> Il a réalisé qu'il était maintenant dans le corps d'une autre personne alors qu'il pensait être mort. <br> Il apprit qu'il faisait partie du Culte Démoniaque et maîtrisait maintenant l'art martial du Dieu Céleste Démoniaque. Le corps dans lequel il se trouve appartenait à l'héritier fou qui ne faisait que convoiter les femmes. <br> Yang se demande pourquoi cela lui est arrivé et pourquoi il se retrouve dans ce corps en particulier.`,
      background_image: "images/I_Reincarnated_As_The_Crazed_Heir.jpg",
    },
    {
      name: "Damn Reincarnation",
      released: "2022-06-22",
      metacritic: 9.7,
      description:
        "Le guerrier Hamel est parti à l'aventure avec ses compagnons pour vaincre les rois démons, mais après être mort juste avant la bataille finale avec les rois démons.<br>Il s'est réincarné en descendant de son compagnon guerrier, Vermouth.<br> Hamel – non, Eugène Coeur de Lion a été réincarné avec le sang du Grand Vermouth.<br>",
      background_image: "images/Damn_Reincarnation.jpg",
    },
    {
      name: "The Dark Magician Transmigrates After 66666 Years",
      released: "2021-06-29",
      metacritic: 9.9,
      description:"Diablo Volfnir, un magicien tout puissant, fut scellé pour l'éternité pour avoir comploté contre les 12 divinités.<br> 66 666 années passèrent et il est désormais..de retour sur Terre.<br>",
      background_image:"images/The_Dark_Magician_Transmigrates_After_66666_Years.jpg",
    },
    {
      name: "Heavenly Demon Instructor",
      released: "2021-12-04",
      metacritic: 9.6,
      description: `Hyeon-Soo, sans compétences, rejoint les chasseurs pour protéger l'humanité contre les monstres qui ont surgi des portails.<br> Il se met en danger pour payer les frais d'hospitalisation de son frère, mais son destin change quand un expert martial vient d'un autre monde pour le coacher.`,
      background_image: "images/Heavenly_Demon_Instructor.jpg",
    },
    {
      name: "The Return of the Disaster-Class Hero",
      released: "2021-10-23",
      metacritic: 9.9,
      description: `Les morts ne peuvent pas parler. <br> Les vivants peuvent inventer n'importe quelle histoire. <br> L'héritage, l'honneur et la richesse peuvent être pris par des mensonges. <br> Mais que se passe-t-il si une personne censée être morte revient à la vie ? <br>`,
      background_image: "images/The_Return_of_the_Disaster-Class_Hero.jpg",
    },
    {
      name: "My Daughter is the Final Boss",
      released: "2022-04-14",
      metacritic: 9.7,
      description: `2040, le monde est en danger de destruction. <br> Seo-Jun est responsable car sa fille unique est à l'origine de cette apocalypse. <br> En tant que père repenti, il perd la vie en essayant de la défendre, mais se réveille soudainement 15 ans plus tôt. <br> C'est l'occasion de sauver la planète et de corriger ses erreurs en tant que parent. <br> Pourra-t-il saisir cette occasion unique ?`,
      background_image: "images/My_Daughter_is_the_Final_Boss.jpg",
    },
    {
      name: "The Heavenly Demon Can't Live a Normal Life",
      released: "2021-06-14",
      metacritic: 9.9,
      description:
        "Démon Céleste' Baek Joong-Hyuk ouvre les yeux en tant que fils aîné de la famille Dimitry.<br>  Connu comme le crétin de la famille Dimitry, bousculé par le deuxième fils.<br> L'opinion du monde entier n'est pas pertinente.<br>",
      background_image: "images/The_Heavenly_Demon_Can’t_Live_a_Normal_Life.jpg",
    },
    {
      name: "The Max Level Hero Has Returned",
      released: "2020-10-26",
      metacritic: 9.9,
      description:
        "Le faible prince d'un pays insignifiant, Davey.<br>  Après être devenu comateux, son âme s'échappa dans un temple où se rassemblaient les âmes des héros.<br>  Il s'est entraîné pendant mille ans et est maintenant revenu comme un héros de niveau max !  « Attendez, je vais vous faire face ! »  L'histoire rafraîchissante de la vie royale et de la vengeance de Davey vient de commencer.<br>",
      background_image: "images/The_Max_Level_Hero_Has_Returned.jpg",
    },
    {
      name: "Return of The Mount Hua Sect",
      released: "2021-03-23",
      metacritic: 10,
      description: `Chung Myung, le 13e disciple de la Secte du Mont Hua, l'un des trois grands épéistes, le Saint épéiste aux Fleurs de Pruniers, a vaincu Chun Ma, le démon céleste qui a semé la destruction dans le monde.<br>    Après la bataille, il rend son dernier souffle au sommet de la montagne du quartier général de la Secte du démon céleste.<br> Mais il renaît 100 ans plus tard dans le corps d'un enfant.<br>`,
      background_image: "images/Return_of_The_Mount_Hua_Sect.jpg",
    },
    {
      name: "Nano Machine",
      released: "2020-06-14",
      metacritic: 9.6,
      description: `La vie remplit d'infortune et d'épreuve de Cheo Yeo-Woon, bâtard et dernier dans l'ordre de succession, prit un tournant après qu'un de ses "descendant" venant du futur ait injecté des Nano Machines dans son corps.<br>`,
      background_image: "images/Nano_Machine.jpg",
    },
    {
      name: "My Dad Is Too Strong",
      released: "2022-03-05",
      metacritic: 9.2,
      description: `Lee Dojun un jeune employé de bureau, obtient un pouvoir hors nome après avoir été transféré dans un monde parallèle à celui de l'ancienne Corée.<br>Après un moment d'inattention, il est réapparu dans son monde d'origine... Avec une surprise !`,
      background_image: "images/My_Dad_Is_Too_Strong.jpg",
    },
    {
      name: "Seoul Station Necromancer",
      released: "2022-04-29",
      metacritic: 8.6,
      description: `Lorsque l'ancien lycéen Kang Woojin se retrouve de retour sur Terre après avoir été convoqué de force sur une planète étrangère pendant 20 ans, il découvre rapidement que la Terre n'est pas le même endroit normal qu'il s'en souvenait.<br>    Avec sa force et son âge remis à zéro, observez Kang Woojin alors qu'il se remet sur la voie pour devenir le nécromancien le plus fort de la Terre !`,
      background_image: "images/Seoul_Station_Necromancer.jpg",
    },
    {
      name: "Overgeared",
      released: "2020-02-02",
      metacritic: 9.4,
      description: `Woo-Shin Young, Pseudonyme : Greed.<br>    Dans le jeu de réalité virtuelle le plus populaire au monde, il est abonné à la malchance.<br>    Mais lors d'une quête, sa chance a tourné, il obtint la classe la plus puissante du jeu qui rassemble plus de 2 milliards de joueurs !`,
      background_image: "images/Overgeared.jpg",
    },
    {
      name: "I Regressed As The Duke",
      released: "2020-06-19",
      metacritic: 8.6,
      description: `Le prince Aaron, fils de l'Empereur Gline, est bénéficiaire de la Bénédiction du Dragon.<br>Il est banni à la périphérie du royaume suite à la rébellion menée par son oncle Zerone.<br>Il vit en tant que Duc de Terres de Brahn, jusqu'à ce que Zerone les attaque et les détruise.<br>Gayle, un loyal sujet, se réveille plus jeune à la place d'un Prince Aaron plus jeune et décide de reprendre sa place d'Empereur en développant la terre et en se préparant à l'invasion de Zerone dans 20 ans.`,
      background_image: "images/I_Regressed_As_The_Duke.jpg",
    },
    {
      name: "Second Life Ranker",
      released: "2020-01-29",
      metacritic: 9.2,
      description: `Yeon-woo avait un frère jumeau qui a disparu il y a cinq ans.<br> Un jour, une montre de poche laissée par son frère est retournée en sa possession.<br> À l'intérieur, un journal intime caché dans lequel on pouvait lire  "Quand tu entendras ceci, je serai déjà mort.<br>`,
      background_image: "images/Second_Life_Ranker.jpg",
    },
    {
      name: "Return of The Unrivaled Spear Knight",
      released: "2021-10-02",
      metacritic: 9.6,
      description: `Joshua est revenu en enfance ! Et maintenant l'histoire de sa vengeance épique commence !  Une étoile brillante issue d'une maison du Duché qui a complètement brisé la logique commune selon laquelle un chevalier doit utiliser une épée.<br> Le grand héros qui a mis fin à la longue guerre civile de l'empire.<br> Son nom était « Joshua Sanders ».<br>`,
      background_image: "images/Return_of_The_Unrivaled_Spear_Knight.jpg",
    },
    {
      name: "I Became a Renowned Family's Sword Prodigy",
      released: "2022-06-23",
      metacritic: 8.6,
      description: `Baek Woojin est le plus jeune fils d'une famille d'épéistes renommés qui n'a ni talent pour l'épée, ni une Aura impressionnante.<br> Bien qu'il ait été déshonoré par sa propre famille et tué, il se réincarne en propriétaire d'une épée magique.<br> Son seul objectif est la destruction de sa propre famille.<br> `,
      background_image: "images/I_Became_a_Renowned_Family’s_Sword_Prodigy.jpg",
    },
    {
      name: "Talent-Swallowing Magician",
      released: "2022-01-01",
      metacritic: 9.2,
      description: `Elric Melvinger.<br>  Le seul héritier de la prestigieuse famille magique.<br>  Même s'il possédait un talent inné, celui-ci, étant trop grand, l'empêchait d'apprendre la magie.<br>  En revanche, il reçut par la suite une bénédiction laissée par ses ancêtres !`,
      background_image: "images/Talent-Swallowing_Magician.jpg",
    },
    {
      name: "The Lord Coins",
      released: "2021-04-30",
      metacritic: 9.4,
      description: `Le marché aux pièces qui va au-delà des dimensions, Un nouveau venu est apparu et a mis le Centre de Commerce Dimensionnel sens dessus dessous !  Erun Steelguard, l'ennemi de tous les commerçants.<br>  Il vivait en fait sa deuxième vie, après avoir perdu toute cette richesse dans le commerce dimensionnel et avoir connu une mort tragique.<br>`,
      background_image: "images/The_Lord_Coins.jpg",
    },
    {
      name: "Academy Undercover Professor",
      released: "2022-06-04",
      metacritic: 9.2,
      description: `Je n'ai pas de talent ou de capacité spéciale, mais mes connaissances terrestres me donnent un avantage dans ce nouveau monde avec de la magie.<br>Les progrès scientifiques sont rapides, mais la magie stagne en raison de la tradition.<br>J'utilise mes connaissances pour faire des choses que les autres sorciers ne peuvent pas imaginer, mais je suis devenu malgré moi un professeur sous couverture pour une société secrète à l'académie de Sören.`,
      background_image: "images/Academy_Undercover_Professor.jpg",
    },
  
    {
      name: "Swordmaster Youngest Son",
      released: "2022-04-30",
      metacritic: 9.6,
      description: `Jin Runcandel est un fils d'un grand maître épéiste qui a été exclu de son clan et a connu un destin tragique, mais a reçu une seconde chance de la part d'un Dieu.<br>Il doit utiliser son nouveau pouvoir pour le bien et tenter de devenir le maître épéiste le plus fort du monde.`,
      background_image: "images/Swordmaster_Youngest_Son.jpg",
    },
    {
      name: "The Greatest Estate Developer",
      released: "2022-09-29",
      metacritic: 9.4,
      description: `Suho Kim, un étudiant en génie civil, se retrouve dans le corps de Lloyd Frontera, un noble paresseux dans un roman fantastique.<br>Avec ses compétences en ingénierie, il conçoit des inventions pour changer son destin et celui de sa nouvelle famille en dette.<br>Il est aidé par un hamster géant, un chevalier et la magie du monde pour construire un avenir meilleur.`,
      background_image: "images/The_Greatest_Estate_Developer.jpg",
    },
    {
      name: "Reaper of the Drifting Moon",
      released: "2022-07-15",
      metacritic: 8.6,
      description: `Pyo Wol a été kidnappé à 7 ans et soumis à des conditions inhumaines.<br>Il a été affamé, empoisonné et battu pour devenir l'arme humaine parfaite.<br>Cependant, il ne se laissera pas briser et s'est promis de survivre pour se venger.`,
      background_image: "images/Reaper_of_the_Drifting_Moon.jpg",
    },
    {
      name: "Heavenly Inquisition Sword",
      released: "2022-10-31",
      metacritic: 9.4,
      description: `Yeon Jeokha était maltraité en tant qu'enfant d'une concubine.<br>Il a été emprisonné, mais a appris des arts martiaux hors du commun et s'est échappé.<br>Il est maintenant l'unique successeur de l'épée de l'Inquisition Céleste et son aventure débute.`,
      background_image: "images/Heavenly_Inquisition_Sword.jpg",
    },
    {
      name: "Standard of Reincarnation",
      released: "2022-08-10",
      metacritic: 9.2,
      description: `Daven, un soldat martial sans bras droit de la famille Samion, a surpassé l'héritier considéré comme un génie malgré le mépris.<br>Il a été trahi par sa famille et a eu une fin malheureuse, mais a été réincarné avec deux bras, une nouvelle famille, un corps doué, son expérience passée et même la bénédiction d'un dieu.<br>Après sa réincarnation, tout a changé et il a commencé une nouvelle vie.`,
      background_image: "images/Standard_of_Reincarnation.jpg",
    },
    {
      name: "How To Live As a Villain",
      released: "2021-11-14",
      metacritic: 9.2,
      description: `Seong-Hoon a été choisi pour participer à un grand jeu pour sélectionner le successeur de Dieu.<br>Il se retrouve dans un autre monde similaire à un jeu où les joueurs coopèrent et s'entretuent.<br>Seong-Hoon, sans talent, utilise des ruses malhonnêtes pour devenir un joueur tout-puissant.`,
      background_image: "images/How_To_LiveAs_a_Villain.jpg",
    },
    {
      name: "Omniscient Reader’s Viewpoint",
      released: "2020-09-13",
      metacritic: 9.8,
      description: `C'est un développement que je connais".<br>Dès qu'il a pensé ça, le monde a été détruit et un nouvel univers s'est développé.<br> La nouvelle vie d'un lecteur ordinaire commence dans le monde du roman, un roman que lui seul a terminé.<br>`,
      background_image: "images/Omniscient_Reader’s_Viewpoint.jpg",
    },
    {
      name: "Murim Login",
      released: "2022-04-22",
      metacritic: 9.6,
      description: `Jin Tae-Kyung est un chasseur de bas rang dans un monde où les chasseurs chassent les monstres qui viennent de Gates.<br>Accidentellement connecté à un jeu de arts martiaux en VR, Tae-Kyung connaît des hauts et des bas mais finit par s'échapper de ce monde en y gagnant force et compétences.<br>Il continue à vivre en tant que chasseur, mais décide de retourner dans le monde du Murim pour ses amis PNJ.`,
      background_image: "images/Murim_Login.jpg",
    },
    {
      name: "The S-Classes That I Raised",
      released: "2021-11-08",
      metacritic: 9.2,
      description: `Un chasseur de rang F.<br>  Lui, ce hyung de rang F aussi inutile que pathétique qui avait entraîné dans sa propre chute son incroyable frère de rang S.<br>  Moi, qui avais vécu sans réelle conviction une vie désastreuse, qui avait fini par ruiner la vie de mon frère et me faire régresser par la suite.<br>`,
      background_image: "images/The_S-Classes_That_I_Raised.jpg",
    },
    {
      name: "Warrior High School – Dungeon Raid Department",
      released: "2022-10-02",
      metacritic: 9.6,
      description: `Dans un monde où la Terre a fusionné avec un autre monde, il existe des donjons remplis de monstres que les aventuriers peuvent explorer. La plus prestigieuse école en Corée du Sud, Warrior High School, forme ces aventuriers.<br>Son pere, Yoo Jaryong, autrefois considéré comme le plus grand aventurier d'Asie, est accusé à tort, il doit faire du trafic de donjons pour payer les soins de son père malade.<br>Il rencontre un adolescent et retrouve son rêve perdu en cachant son identité.`,
      background_image: "images/Warrior_High_School–Dungeon_Raid_Department.jpg",
    },
    {
      name: "The World After The End",
      released: "2022-02-07",
      metacritic: 9.2,
      description: `Les humains sont appelés à devenir des "Marcheurs" pour nettoyer la tour et sauver le monde, mais avec la découverte de la "pierre de régression" ils peuvent retourner dans le passé.<br>Le groupe "Carpe Diem" est formé pour sauver l'humanité mais le dernier Marcheur atteignant l'étage 100 ne sait plus quoi croire.<br>L'histoire est celle d'un homme qui n'a pas régressé alors que tous les autres ont retourné dans le passé.`,
      background_image: "images/The_World_After_The_End.jpg",
    },
    {
      name: "Player Who Can’t Level Up",
      released: "2021-02-28",
      metacritic: 9.4,
      description: `Kim Gigyu, joueur éveillé à l'âge de 18 ans, pensait que sa vie serait remplie de succès en grimpant « la tour » et en fermant « les portes »..<br>Cependant, après avoir terminé le tutoriel, il était au niveau 1 ; Après une chasse au gobelin, il était encore niveau 1 ; 5 ans après, il était toujours niveau 1.<br>  « Qui aurait cru que ce genre de joueur pouvait exister..<br>? »`,
      background_image: "images/Player_Who_Can’t_Level_Up.jpg",
    },
    {
      name: "I Obtained a Mythic Item",
      released: "2022-06-12",
      metacritic: 9.6,
      description: `Min JaeHyun se trouve dans un monde où Yggdrasil est apparu et a causé la destruction avec des créatures démoniaques.<br>Des humains spéciaux ont un système pour survivre, mais Min regrette ses mauvais choix passés.<br>Un jour, il obtient un objet mythique qui pourrait changer son destin.`,
      background_image: "images/I_Obtained_a_Mythic_Item.jpg",
    },
    {
      name: "Player Who Returned 10 000 Years Later",
      released: "2022-07-30",
      metacritic: 8.8,
      description: `Du jour au lendemain, il s'est retrouvé en Enfer.<br> Tout ce qui lui restait, était sa foi en Dieu et son désir de survivre.<br>Du 1er au 9000e cercle des Enfers, il a absorbé des dizaines, des centaines de milliers de démons.<br> Même les sept grands ducs des Abysses se prosternèrent devant lui.<br>Il n'y a ni nourriture ni divertissement.<br> Il n'y a en enfer qu'un désert aride et de terribles démons.<br>Et il a décidé de retourner sur Terre, dix mille ans plus tard.<br>`,
      background_image: "images/Player_Who_Returned_10_000_Years_Later.jpg",
    },
    {
      name: "Boundless Necromancer",
      released: "2022-12-17",
      metacritic: 9.6,
      description: `Jamais auparavant, je n'aurais pensé pouvoir devenir un chasseur.<br>Je ne croyais pas en avoir la chance.<br>Et pourtant, ce ne fut pas le cas.<br>「 La Tour des épreuves a sélectionné tous les candidats potentiels sur Terre. 」<br>「 Veuillez sélectionner votre niveau de difficulté. 」<br>「 La difficulté choisie sera en corrélation directe avec vos récompenses.<br> 」On m'a donné une occasion à présent.<br>Une occasion en or qui plus est.<br>`,
      background_image: "images/Boundless_Necromancer.jpg",
    },
    {
      name: "Return of the SSS-Class Ranker",
      released: "2022-08-14",
      metacritic: 9.2,
      description: `Rokan était le « roi de la violence » qui régnait en maître dans le jeu de réalité virtuelle « The Lord ».<br> Malheureusement, l'ordre d'assassinat émis par une guilde ennemie lui a fait tout perdre.<br> À sa grande surprise, lors de son reveil, il était revenu trois ans en arrière !<br>Une nouvelle histoire commence alors que Rokan, qui a voyagé dans le temps, grimpe pour revenir au sommet !`,
      background_image: "images/Return_of_the_SSS-Class_Ranker.jpg",
    },
    {
      name: "Poison-Eating Healer",
      released: "2022-12-11",
      metacritic: 9.6,
      description: `Cheon Haesun est le protagoniste qui est gravement malade en raison de divers poisons.<br>Cheon Haesun, qui n'a jamais été le bienvenu nulle part, verra son périple de devenir le chasseur le plus fort sur une Terre où des donjons et des monstres ont fait irruption !`,
      background_image: "images/Poison-Eating_Healer.jpg",
    },
    {
      name: "Champion Path to Murim",
      released: "2022-09-10",
      metacritic: 9.2,
      description: ` Kim Sanghyuk, un champion connu sous le nom de "Mister Perfect", renaît dans le monde de Murim et décide de forger une nouvelle légende en mélangeant différents arts martiaux.`,
      background_image: "images/Champion_Path_to_Murim.jpg",
    },
    {
      name: "Demon Lord Martial Arts Ascension",
      released: "2022-09-18",
      metacritic: 9.4,
      description: `"Seigneur Démon."<br>C'est…<br>Comment ils m'appelaient dans ma vie passée, avant que je ne devienne humain.`,
      background_image: "images/Demon_Lord_Martial_Arts_Ascension.jpg",
    },
    {
      name: "Regressor Instruction Manual",
      released: "2021-10-23",
      metacritic: 9.0,
      description: `Un jour, Lee Ki-Young est appelé dans un espace non identifié avec d'autres personnes. Il reçoit un avertissement l'invitant à utiliser ses compétences et ses attributs pour survivre.<br>En vérifiant ses compétences, il découvre que ses valeurs sont les plus faibles, mais découvre un attribut qui lui est accordé : la capacité de voir les compétences et les fenêtres de statut des autres personnes.<br>Pour survivre, il décide de se servir des talents des autres et trouve un allié en la personne de Kim Hyun-Sung, un homme qui a déjà vécu la fin du monde et qui a l'intention de le faire avec lui jusqu'à la fin.`,
      background_image: "images/Regressor_Instruction_Manual.jpg",
    },
    {
      name: "Star Instructor Master Baek",
      released: "2022-11-05",
      metacritic: 9.0,
      description: `Suryong Baek, le meilleur instructeur du culte démoniaque, se fait tuer.<br> Mais il se réveille dans le corps d'un homme qui enseigne les arts martiaux dans un petit dojo de campagne.<br> Bien que son nouveau corps soit faible et ne puisse pas cultiver l'énergie interne, Suryong connaît cette situation et la méthode pour guérir.<br> Cependant, la cure demande beaucoup d'argent ce qui va l'amener à passer plusieurs épreuves pour tenter de devenir le meilleur instructeur de l'académie du dragon azur.<br> Parviendra-t-il à devenir le plus grand maître malgré les vestiges du culte démoniaque qui commencent à apparaître ?`,
      background_image: "images/Star_Instructor_Master_Baek.jpg",
    },
    {
      name: "Wandering Warrior of Wudang",
      released: "2021-09-08",
      metacritic: 8.8,
      description: `Un jour, Hyeokyeon Mugang entend la Faucheuse prononcer son nom trois fois.<br>Cependant, il survive en avalant l'Herbe de l'Immortalité.<br>Il se réveille entouré de vieillards et découvre qu'il a été réincarné dans le corps d'un garçon de courses dans un clan de chamans.<br>Hyeokyeon décide de devenir le meilleur disciple possible et de poursuivre le chemin du chaman.`,
      background_image: "images/Wandering_Warrior_of_Wudang.jpg",
    },
    {
      name: "The Novel Extra (Remake)",
      released: "2022-08-27",
      metacritic: 9.6,
      description: `En se réveillant, Kim Hajin se retrouve dans un monde familier, mais dans un corps qui lui ne lui est pas familier.<br>Un monde qu'il a lui-même créé, mais jamais terminée.<br>Il était devenu l'un des personnages de sont novel, un personnage random sans importance pour l'histoire.<br>Le seul moyen de s'échapper est de rester sur l'intrigue principale.<br>Cependant, il découvre rapidement que le monde n'est pas exactement identique à sa création.<br>`,
      background_image: "images/The_Novel_Extra_(Remake).jpg",
    },
    {
      name: "Sleeping Ranker",
      released: "2022-03-17",
      metacritic: 8.6,
      description: `Prêtez attention à l'histoire de la Classe de Rang Dieu, le descendant de Thananos, l'inarrêtable Hyunsung.<br>`,
      background_image: "images/Sleeping_Ranker.jpg",
    },
    {
      name: "Return Of The Shattered Constellation",
      released: "2021-11-29",
      metacritic: 8.8,
      description: `Un humain devient dieu et connaît une perte totale de ses pouvoirs divins.<br>Il change de nom en "Lee Chang-Seon" et est contacté par le maître du monde du néant, Thanatos, qui lui propose de travailler ensemble.<br>Lee Chang-Seon décide de se venger des dieux qui l'ont envoyé en enfer et commence une nouvelle vie.`,
      background_image: "images/Return_Of_The_Shattered_Constellation.jpg",
    },
    {
      name: "Heavenly Sword Grand Saga",
      released: "2022-06-30",
      metacritic: 8.0,
      description: `Un disciple avec six maîtres doit sauver le monde des conflits causés par ceux qui se considèrent comme des "élus" des cieux.<br>Il se résout de devenir l'épée qui transpercera les cieux, mais avant cela, il doit d'abord perdre du poids.`,
      background_image: "images/Heavenly_Sword_Grand_Saga.jpg",
    },
    {
      name: "The Hero Returns",
      released: "2022-03-03",
      metacritic: 9.3,
      description: `Le plus fort héros de l'humanité, Kim Sung In.<br>Il a tout risqué et s'est démené mais..<br>il n'a pas pu empêcher la destruction du monde.<br>Mais sa légende ne fait que commencer puisqu'il revient 20 ans dans le passé.<br>`,
      background_image: "images/The_Hero_Returns.jpg",
    },
    {
      name: "Heavenly Martial God",
      released: "2021-09-19",
      metacritic: 9.7,
      description: `Ha Hoo Young, le plus grand artiste martial, voulait devenir un saint mais a été refusé à cause de son karma sanglant.<br>Il a été réincarné 60 ans plus tard en tant que Namgoong Hyuk, le deuxième seigneur de la famille Namgoong, mais a perdu toute son énergie interne et est bloqué par l'énergie des Neuf Yin.`,
      background_image: "images/Heavenly_Martial_God.jpg",
    },
    {
      name: "Maxed Out Leveling",
      released: "2021-09-30",
      metacritic: 8.9,
      description: `Cha Shin Hyeon est un expert en arts martiaux, reconnu dans Jianghu comme le plus puissant.<br>Il revient sur Terre pour découvrir que le monde a beaucoup changé et est maintenant peuplé de monstres et de chasseurs.<br>Cependant, il n'est pas découragé car il est déjà au niveau maximum des arts martiaux et prêt à recommencer au niveau 1.`,
      background_image: "images/Maxed_Out_Leveling.jpg",
    },
    {
      name: "SSS-Class Suicide Hunter",
      released: "2020-12-31",
      metacritic: 9.5,
      description: `Kim Gong Ja reçoit une capacité de la part de la Tour, mais il doit mourir pour en bénéficier. Après avoir assisté au meurtre de la Sainte par l'Empereur des flammes, Yoo Soo Ha, Kim Gong Ja se fait tuer et copie l'une des capacités de l'Empereur des flammes. Pour accomplir sa vengeance, il décide de se suicider 4090 fois afin de remonter dans le temps.`,
      background_image: "images/SSS-Class_Suicide_Hunter.jpg",
    },
    {
      name: "The Second Coming of Gluttony",
      released: "2021-02-23",
      metacritic: 8.7,
      description: `C'était un addict aux jeux, un raté, une personne méprisable.<br> Mais, un rêve fugace, qui pourrait bien ne pas être un rêve du tout, réveille des sens qu'il avait jusqu'alors perdu.<br> Possédant une capacité vraiment unique, il va se servir de celle-ci et du rêve pour forger sa destinée dans un monde maintenant connu sous le nom du Paradis Perdu.<br>`,
      background_image: "images/The_Second_Coming_of_Gluttony.jpg",
    },
  ];